import React from "react";
import Head from "next/head";

import UserContext from "../context/userdata";
import UserInfo from "../components/userinfo";
import AboutMe from "../components/aboutme";
import Social from "../components/social";
import Prof_info from "../components/prof_info";
import ChangePassword from "../components/changepassword";
import Intrest from "../components/intrest";

const Dashboard = () => {
  const { user, setUser } = React.useContext(UserContext);

  return (
    <div>
      <Head>
        <title>Profile | Cipher School </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main className="w-screen">
        {console.log(user)}
        <UserInfo />
        <AboutMe />
        <Social />
        <Prof_info />
        <ChangePassword />
        <Intrest />
      </main>
    </div>
  );
};

export default Dashboard;
