import React from "react";
import Head from "next/head";

import UserContext from "../context/userdata";
import UserInfo from "../components/userinfo";
import AboutMe from "../components/aboutme";

const Dashboard = () => {
  const { user, setUser } = React.useContext(UserContext);

  return (
    <div>
      <Head>
        <title>Profile | Cipher School </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main className="w-screen">
        {console.log(user)}
        <UserInfo />
        <AboutMe />
      </main>
    </div>
  );
};

export default Dashboard;
